// 보관함 CRUD(Site/Category/Secret) 도메인 에러 코드.
export const STORE_ERRORS = {
    SITE_NOT_FOUND: "SITE_NOT_FOUND",
    CATEGORY_NOT_FOUND: "CATEGORY_NOT_FOUND",
    CATEGORY_SITE_MISMATCH: "CATEGORY_SITE_MISMATCH",
    SECRET_NOT_FOUND: "SECRET_NOT_FOUND",
    VAULT_LOCKED: "VAULT_LOCKED",
    DECRYPT_FAILED: "DECRYPT_FAILED",
    CSRF_INVALID: "CSRF_INVALID",
} as const
