// 월 문자열 검증 정규식 "YYYY-MM"(01–12). DTO·서비스 공용.
export const MONTH_RE = /^\d{4}-(0[1-9]|1[0-2])$/

// 자산(가계부) 도메인 에러 코드.
export const ASSET_ERRORS = {
    EXPENSE_NOT_FOUND: "EXPENSE_NOT_FOUND",
    EXPENSE_DUPLICATE: "EXPENSE_DUPLICATE",
    RECURRING_NOT_FOUND: "RECURRING_NOT_FOUND",
    CIPHERTEXT_INCOMPLETE_ASSET: "CIPHERTEXT_INCOMPLETE_ASSET",
    INVALID_MONTH: "INVALID_MONTH",
    INCOME_NOT_FOUND: "INCOME_NOT_FOUND",
    ASSET_CATEGORY_NOT_FOUND: "ASSET_CATEGORY_NOT_FOUND",
    ASSET_CATEGORY_DUPLICATE: "ASSET_CATEGORY_DUPLICATE",
    ASSET_CATEGORY_CODE_DUPLICATE: "ASSET_CATEGORY_CODE_DUPLICATE",
    SAVINGS_ACCOUNT_NOT_FOUND: "SAVINGS_ACCOUNT_NOT_FOUND",
    SAVINGS_BOX_NOT_FOUND: "SAVINGS_BOX_NOT_FOUND",
} as const
